### ISSUE TITLE
Writings in the landing page not very clear

### ISSUE THREAD

**Issue by sarnava1** [fossasia/gci18.fossasia.org#68] opened 2018-10-27 04:48 UTC
**Actual Behaviour**
The white writings in the landing page is not clear

The white writings : 
Creating collaborative open-source technologies.
Connecting Open Tech Communities all over Asia with Developers and Creators
in the FOSSASIA Network.
 **Expected Behaviour**
We should make the writings more clear

**Steps to reproduce it**
Just open the FOSSASIA site
**Screenshots of the issue**
![writingsnotclear](https://user-images.githubusercontent.com/25319565/47599694-eef10d00-d9d0-11e8-9709-a879b61fc2f1.png)
**Would you like to work on the issue?**
Only for GCI students

**Comment by sarnava1** [comment] 2018-10-27 07:13
Hello @mariobehling @tabesin @liveHarshit can you add the label of gci too? I am not getting any such option to add labels.

**Comment by STEdirisuriya** [comment] 2018-10-30 12:57
I would like to work on this.

**Comment by sarnava1** [comment] 2018-10-30 13:07
@STEdirisuriya sure!!

**Comment by liveHarshit** [comment] 2018-10-30 14:29
@STEdirisuriya try to add a shadow effect in the background.

**Comment by STEdirisuriya** [comment] 2018-11-01 05:07
@liveHarshit ok. I'll

**Comment by STEdirisuriya** [comment] 2018-11-02 19:31
I added the PR and it's merged. But however, after another PR, it's get lost some.

**Comment by STEdirisuriya** [comment] 2018-11-03 06:37
I think this should closed now. @sarnava1

**Closed** 2018-11-15 19:22 UTC
Labels: GCI Task, good first issue

**Comment by jogendra** [comment] 2018-11-15 20:18
@fragm3 @STEdirisuriya I think the issue is still there.
