### ISSUE TITLE
Some mentors are missing from the Mentors section

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/gci18.fossasia.org#96] opened 2018-10-28 12:21 UTC
**Actual Behaviour**
* Some mentors are missing from the Mentors section

**Expected Behaviour**
* All mentors should be present in the PR

List of mentors - 
- [x] Shubham Kumar
- [x] Harshit Khandelwal
- [x] tabesin
- [x] Shashank Kumar
- [x] Saurabh Srivastava 
- [x] Akshat Garg
- [x] Arundhati Gupta
- [x] Jogendra Singh
- [x] Anshuman Verma
- [x] Sanskar Jethi
- [x] Akshat Jain
- [x] Mohit Sharma
- [x] Prateek Chanda
- [x] Mohit Kumar
- [ ] Hon Nguyen
- [x] Abishek V Ashok
- [x] Rohit Potter
- [x] Shubham Gupta
- [x] Nikit Bhandari
- [ ] Tarun Kumar
- [x] Sridhar Jajoo 
- [ ] Simranpreet kaur

Note - Please add 1 mentor per PR so that all the students get a chance to work on it.

**Comment by jogendra** [comment] 2018-10-29 17:36
@hpdang Yes, there are more mentors to be added. The issue is automatically closed when I merged the PR related to the issue.

**Comment by arundhati24** [comment] 2018-11-06 16:23
If a GCI student adds a mentor and his/her details, esp. photograph, please request the respective mentor to review the PR before merging.

**Comment by akshatnitd** [comment] 2018-11-06 16:29
Yes, please take the consent from the mentors before adding his/her personal details. And make sure to tag him/her in the PR.

**Comment by akshit15013** [comment] 2018-11-12 08:07
I am claiming this issue

**Comment by akshit15013** [comment] 2018-11-12 10:49
Can I claim this issue?

**Comment by jogendra** [comment] 2018-11-12 10:50
@akshit15013 yes, go ahead and make a PR.

**Comment by RahulMetre03** [comment] 2018-11-14 17:52
#367

**Comment by arihantbansal** [comment] 2018-12-08 09:46
Added mentor Sridhar Jajoo.

**Comment by NishithP2004** [comment] 2018-12-28 15:02
@akshatnitd Please close this issue as well .

**Closed** 2018-12-28 15:06 UTC
Labels: GCI Task, good first issue
