### ISSUE TITLE
My first Issue

### ISSUE THREAD

**Issue by RahulMetre03** [fossasia/gci18.fossasia.org#147] opened 2018-10-30 15:21 UTC
**Actual Behaviour**

Currently, no instructions are present to run https://gci18.fossasia.org/ locally on your computer.
**Expected Behaviour**

Add Instructions for running https://gci18.fossasia.org/ locally on your computer.

**Would you like to work on the issue?**

No

**Comment by abishekvashok** [comment] 2018-10-31 12:06
Duplicate of #140

**Closed by abishekvashok** 2018-10-31 12:06 UTC
